swagger: '2.0'
info:
    x-ibm-name: petstore-api
    title: 'PetStore API'
    version: 1.0.1
schemes:
    - https
host: $(catalog.host)
basePath: /petstore-api
consumes:
    - application/json
produces:
    - application/json
securityDefinitions:
    clientIdHeader:
        type: apiKey
        in: header
        name: X-IBM-Client-Id
security:
    -
        clientIdHeader: []
x-ibm-configuration:
    testable: true
    enforced: true
    cors:
        enabled: true
    assembly:
        execute:
            - {invoke: {target-url: $(target-url)$(request.path)}}
    phase: realized
paths: {}
definitions: {}
tags: []
